### ISSUE TITLE
Im confused

### ISSUE THREAD

**Issue by BRokk2013** [7zennos/Gorilla-Tag-ShibaGT-Gold-Mod-Menu#1]
I realized that shibagt gold is paid but when i got it from here i checked for viruses but there was none. is this okay to use

**Comment by iiDk-the-actual** [comment]
> virus check menu
> no viruses
> is this safe to use?

**Comment by MrBanana01** [comment]
it doesn't get detected because the dll itself is not the rat, when using it for the first time it then downloads a different thing that gets hidden on your pc and those files that get downloaded send your info to shibas servers.

**Comment by FlipperFlopper99** [comment]
damn didnt know that

**Comment by ElliotsTwinGT** [comment]
so is it a rat/virus?

**Comment by MrBanana01** [comment]
yep

**Comment by iiDk-the-actual** [comment]
no
